### ISSUE TITLE
Sometimes plots don't show correctly

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/BenchmarkProfiles.jl#11]
Like 
![elapsed-time-optimize trunk-optimtrn](https://user-images.githubusercontent.com/1068752/26956914-aa8344d4-4c97-11e7-862a-afcb83079709.png)
Not sure if it's a Inf or NaN. Still investigating.

**Comment by dpo** [comment]
Can we close this in favor or #12?

**Comment by abelsiqueira** [comment]
Yes, thanks.
