### ISSUE TITLE
Wrong on 0.6

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/BenchmarkProfiles.jl#12]
Wrong on 0.6 because minimum of NaN and value returns NaN now.

**Comment by Goysa2** [comment]
I think I have the same problem. Here is a performance profile: [http://imgur.com/a/9Tc7Y](url) some lines are cut too early.

**Comment by dpo** [comment]
Thanks both! #13 should fix it.

**Comment by dpo** [comment]
Fixed in #13.
