### ISSUE TITLE
return a CSV or Julia vectors instead of a plot

### ISSUE THREAD

**Issue by lkapelevich** [JuliaSmoothOptimizers/BenchmarkProfiles.jl#49]
Thanks for making this package! 

I want to build performance profiles, but instead of getting a julia plot, keep the raw plot coordinates as julia vectors, so they can be used to make a plot outside of julia. It looks pretty simple to return the `rs[xidx]` and `xs[xidx]` in `performance_profile` (and account for the stepping in the line graph), happy to make a pr.

**Comment by abelsiqueira** [comment]
Hi @lkapelevich. I think that a function that returns vectors will be ok. A PR is most welcome.

**Comment by lkapelevich** [comment]
closed by #50
