### ISSUE TITLE
Package rename

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/BenchmarkProfiles.jl#5]
We should rename this package. The current name isn't sufficiently explicit to make it in METADATA. I thought of BenchmarkProfiles. Any other suggestions?
@JuliaSmoothOptimizers/continuousoptimizers

**Comment by abelsiqueira** [comment]
I think not. PerformanceProfiles would be more familiar, but this includes data profiles too. BenchmarkProfiles might draw more attention.

**Comment by dpo** [comment]
@vepiteski Do you have other suggestions or does BenchmarkProfiles sound good?

**Comment by vepiteski** [comment]
Le 2016-10-04 à 09:36, Dominique a écrit :
>
> @vepiteski <https://github.com/vepiteski> Do you have other 
> suggestions or does BenchmarkProfiles sound good?
>

I think it is OK.

PerformanceProfiles is more common, but as Abel remarked, the Pkg also 
provides data profiles.

So, BenchmarkProfiles seems "optimal".

JPD

**Comment by dpo** [comment]
Thank you. I renamed the repository. Now I'll update the contents.

**Comment by dpo** [comment]
Done in #6.
